language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar --prefer-source --dev install
  - printf "\n" | pecl install imagick

script:
  - vendor/bin/phpspec run
